version: "3.6"

services:
  db:
    image: elestio/mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/dump:/docker-entrypoint-initdb.d
    ports:
      - 172.17.0.1:56151:3306

  ojs:
    user: 0:0
    image: "pkpofficial/ojs:latest"
    restart: always
    #    env_file:
    #      - .env
    ports:
      - "172.17.0.1:26708:443"
      # - "${HTTPS_PORT:-443}:443"
    # environment:
    #   - OJS_CLI_INSTALL=1
    #   - SERVERNAME=${DOMAIN}
    #   - OJS_DB_HOST=db
    #   - OJS_DB_USER=${MYSQL_USER}
    #   - OJS_DB_PASSWORD=${MYSQL_PASSWORD}
    #   - OJS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      #      - ./volumes/logs/app:/var/log/apache2
      #      # WARNING: You can only enable file-volumes if file exists in the container.
      # - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
    #      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
    #      - ./volumes/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

  pma:
    image: elestio/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - "172.17.0.1:18920:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
